# 基本配置
title: 邓果垚的技术博客
description: 专注于分享技术经验、编程技巧和行业洞察的个人博客
author: 邓果垚
email: 741533684@qq.com

baseurl: "" # 网站的子路径，例如 /blog
url: "https://rabbitdeng.github.io" # 网站的基本域名和协议
repository: rabbitdeng/rabbitdeng.github.io # GitHub仓库格式：username/repo-name

# 构建设置
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/ # 文章链接格式

# 排除处理的文件和目录
# 以下项目默认不会被处理
# 任何列在`exclude:`键下的项目都会自动添加到内部"默认列表"
#
# 被排除的项目可以通过在`include:`列表中明确列出目录或文件路径来处理
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 分页设置
paginate: 5
paginate_path: "/page:num/"
